server:
  port: 7077

spring:
  application:
    name: FeedService

  datasource:
    url: jdbc:postgresql://localhost:5432/TrustNet
    username: postgres
    password: Suvam@123
    driver-class-name: org.postgresql.Driver

    hikari:
      connection-timeout: 10000

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    open-in-view: false

    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: com.social.FeedService.Event
        spring.json.use.type.headers: false

    listener:
      ack-mode: record

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true